// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {translator} from '../models';

export function DeleteConfig(arg1:string):Promise<void>;

export function GetConfigs():Promise<Array<translator.Config>>;

export function PauseListening():Promise<void>;

export function SaveConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function StartListening(arg1:string):Promise<void>;

export function StopListening():Promise<void>;

export function TestConnection(arg1:string):Promise<void>;
