// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteConfig(arg1) {
  return window['go']['main']['App']['DeleteConfig'](arg1);
}

export function GetConfigs() {
  return window['go']['main']['App']['GetConfigs']();
}

export function GetFullConfig(arg1) {
  return window['go']['main']['App']['GetFullConfig'](arg1);
}

export function PauseListening() {
  return window['go']['main']['App']['PauseListening']();
}

export function SaveConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function StartListening(arg1) {
  return window['go']['main']['App']['StartListening'](arg1);
}

export function StopListening() {
  return window['go']['main']['App']['StopListening']();
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
